<?php

declare(strict_types=1);

namespace Effectra\SqlQuery\Operations;

use Effectra\SqlQuery\Attribute;
use Effectra\SqlQuery\Build\BuildAction;
use Effectra\SqlQuery\Build\RunBuilder;

/**
 * Class Delete
 *
 * This class represents an SQL "DELETE" operation for deleting records from a database table.
 *
 */
class Delete extends Attribute
{
    use OperationsTrait;

    /**
     * Constructor for the Delete class.
     *
     * @param string $table The name of the table from which records will be deleted.
     */
    public function __construct(string $table)
    {
        $this->setAttribute('table_name', $table);
        $this->setAttribute('operation', 'delete');
    }

    /**
     * Get the SQL query generated by the Delete operation.
     *
     * @return string
     */
    public function getQuery(): string
    {
        return (string) new RunBuilder($this->getAttributes(), BuildAction::DELETE);
    }

    /**
     * Convert the Delete operation to a string, returning the generated SQL query.
     *
     * @return string
     */
    public function __toString(): string
    {
        return $this->getQuery();
    }
}
