<?php

declare(strict_types=1);

namespace Effectra\SqlQuery\Operations;

use Effectra\SqlQuery\Attribute;
use Effectra\SqlQuery\Build\BuildAction;
use Effectra\SqlQuery\Build\RunBuilder;

/**
 * Class Truncate
 *
 * This class represents an SQL TRUNCATE TABLE operation for quickly removing all rows from a table.
 *
 */
class Truncate extends Attribute
{

    /**
     * Constructor for the Truncate class.
     *
     * @param string $table The name of the table to truncate.
     */
    public function __construct(string $table)
    {
        $this->setAttribute('table_name', $table);
        $this->setAttribute('operation', 'truncate');
    }

    /**
     * Get the SQL query generated by the Truncate operation.
     *
     * @return string The SQL query.
     */
    public function getQuery(): string
    {
        return (string) new RunBuilder($this->getAttributes(), BuildAction::TRUNCATE);
    }

    /**
     * Convert the Truncate operation to a string, returning the generated SQL query.
     *
     * @return string The generated SQL query.
     */
    public function __toString(): string
    {
        return $this->getQuery();
    }
}
