<?php

declare(strict_types=1);

namespace Effectra\SqlQuery\Operations;

use Effectra\SqlQuery\Attribute;
use Effectra\SqlQuery\Build\BuildAction;
use Effectra\SqlQuery\Build\RunBuilder;
use Effectra\SqlQuery\Table;
use Effectra\SqlQuery\Syntax;
use Effectra\SqlQuery\Validation\ArraysValidation;

/**
 * Class Update
 *
 * This class represents an SQL UPDATE operation for modifying existing records in a table.
 *
 */
class UpdateTable extends Attribute
{
    /**
     * Use traits for arrays validation and operations.
     */
    use ArraysValidation, OperationsTrait;

    /**
     * Constructor for the UpdateTable class.
     *
     * @param string $table_name The name of the table to update.
     * @param mixed $table The definition of the table's structure.
     */
    public function __construct(protected string $table_name, protected  $table)
    {
        $this->setAttribute('operation','update_table');
        $this->setAttribute('table_name',$table_name);
        $this->mergeAttribute($this->getTableConstructs());
    }

      /**
     * Get the table constructs, including columns and other attributes.
     *
     * @return array The table constructs.
     */
    public function getTableConstructs(): array
    {
        $table = new Table(new Syntax());
        $table->setTableName($this->getAttribute('table_name'));
        
        call_user_func($this->table, $table);
        return $table->getAttributes();
    }

    /**
     * Get the SQL query generated by the Update operation.
     *
     * @return string The SQL query.
     */
    public function getQuery(): string
    {
        return (string) new RunBuilder($this->getAttributes(), BuildAction::TABLE);
    }

    /**
     * Convert the UpdateTable operation to a string, returning the generated SQL query.
     *
     * @return string The generated SQL query.
     */
    public function __toString(): string
    {
        return $this->getQuery();
    }
}
